version: '3.8'

services:
  gps-api-central:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/gps-api-central:latest
    container_name: gps-api-central
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: postgres_prod
      DB_PORT: 5432
      DB_USERNAME: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: your_db_name
      NODE_ENV: production
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRATION: 24h
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
